name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: your-docker-username/your-app-name:latest
